# Test One Hot LR and Some Tools

In [44]:
import mxnet as mx
from mxnet import gluon
import sys
sys.path.append("/home/elliottqian/Documents/PycharmProjects/deeplearning_notebook/movielens_ctr_project_mxnet")
from gluon_tool.gluon_io import get_csv_file_batch_tier
from gluon_tool.trainer_tool import train_model
from model import One_Hot_LR

In [45]:
test_movielens_path = "/mnt/D/Ubuntu/PycharmProjects/deeplearning_notebook/data/part.csv"
dim_array = [2, 7, 21, 3706, 301]

In [46]:
data_iter = get_csv_file_batch_tier(test_movielens_path, data_shape=(6), batch=2000)

In [47]:
test = next(data_iter)
test

In [48]:
test.data[0]


[[  1.00000000e+00   1.00000000e+00   2.00000000e+00   1.70000000e+01
    1.09000000e+03   1.30000000e+01]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   1.90000000e+01
    1.09000000e+03   1.30000000e+01]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   1.40000000e+01
    1.09000000e+03   1.30000000e+01]
 ..., 
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   2.00000000e+00
    2.13600000e+03   1.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   4.00000000e+00   2.00000000e+01
    2.13600000e+03   1.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   5.00000000e+00   1.30000000e+01
    2.13600000e+03   1.00000000e+00]]
<NDArray 2000x6 @cpu(0)>

In [49]:
from gluon_tool.trainer_tool import get_train_X_y
from model.One_Hot_LR import get_ont_hot_lr

In [50]:
from layer.One_Hot import OneHotLayer
def get_ont_hot_lr(dim_arr, ctx=mx.cpu()):
    """
    :param dim_arr: 各个维度的个数
    :param ctx: 运行环境
    :return:
    """
    my_net = gluon.nn.Sequential()
    with my_net.name_scope():
        my_net.add(OneHotLayer(dim_arr))
        my_net.add(gluon.nn.Dense(1, activation='sigmoid'))
    my_net.initialize(ctx=ctx)
    return my_net

my_lr_network = get_ont_hot_lr(dim_array)
X, y = get_train_X_y(test)

In [51]:
print(str(type(data_iter)))

<class 'mxnet.io.MXDataIter'>


In [59]:
data_iter = get_csv_file_batch_tier(test_movielens_path, data_shape=(6), batch=200000)


In [60]:
def reset(iter_):
    """
    # reset 函数, 用于重头开始迭代
    :param iter_:
    :return:
    """
    type_str = str(type(iter_))
    if "<class 'mxnet.io.MXDataIter'>" == type_str:
        iter_.reset()
        return iter_
    return 1, 0
    pass

In [61]:
yyy = reset(data_iter)

In [66]:
from gluon_tool.trainer_tool import get_trainer
from gluon_tool.trainer_tool import get_log_loss

In [67]:
my_loss = get_log_loss()
my_trainer = get_trainer(my_net=my_lr_network, gd_method='AdaGrad', param_dict={'learning_rate': 0.9})

In [68]:
from mxnet import autograd
from gluon_tool.trainer_tool import train_model

In [69]:
train_model(5, data_iter, my_trainer, my_lr_network, my_loss)


[ 11.47623253]
<NDArray 1 @cpu(0)>



[ 11.91744709]
<NDArray 1 @cpu(0)>



[ 11.72699833]
<NDArray 1 @cpu(0)>



[ 11.82907391]
<NDArray 1 @cpu(0)>



[ 12.06834412]
<NDArray 1 @cpu(0)>



[ 11.15231419]
<NDArray 1 @cpu(0)>



[ 11.91448593]
<NDArray 1 @cpu(0)>



[ 11.71511459]
<NDArray 1 @cpu(0)>



[ 11.82610035]
<NDArray 1 @cpu(0)>



[ 12.06000614]
<NDArray 1 @cpu(0)>



[ 11.12635994]
<NDArray 1 @cpu(0)>



[ 11.87600899]
<NDArray 1 @cpu(0)>



[ 11.54699707]
<NDArray 1 @cpu(0)>



[ 11.51647663]
<NDArray 1 @cpu(0)>



[ 11.46319866]
<NDArray 1 @cpu(0)>



[ 10.13027477]
<NDArray 1 @cpu(0)>



[ 11.20820999]
<NDArray 1 @cpu(0)>



[ 10.62705898]
<NDArray 1 @cpu(0)>



[ 10.76961517]
<NDArray 1 @cpu(0)>



[ 10.52604485]
<NDArray 1 @cpu(0)>



[ 9.59091091]
<NDArray 1 @cpu(0)>



[ 10.31260777]
<NDArray 1 @cpu(0)>



[ 10.31373405]
<NDArray 1 @cpu(0)>



[ 10.27897549]
<NDArray 1 @cpu(0)>



[ 9.9007349]
<NDArray 1 @cpu(0)>


In [38]:
next(data_iter).data[0]


[[  1.   1.   1.   4.  16.   9.]
 [  1.   1.   3.   7.  16.   9.]
 [  1.   0.   2.  14.  16.   9.]
 ..., 
 [  1.   1.   3.  14.  16.   9.]
 [  0.   1.   5.  16.  16.   9.]
 [  1.   1.   1.   4.  16.   9.]]
<NDArray 256x6 @cpu(0)>

In [16]:
my_lr_network(X)


[[ 0.99025005]
 [ 0.98325515]
 [ 0.98103929]
 ..., 
 [ 0.98008794]
 [ 0.96949345]
 [ 0.98368549]]
<NDArray 2000x1 @cpu(0)>

In [18]:
y


[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 1.]
 [ 0.]]
<NDArray 2000x1 @cpu(0)>

In [70]:
data_iter.reset()

In [71]:
from gluon_tool.evaluation import get_auc
get_auc(my_lr_network, data_iter)

0.69282835900469164

In [20]:
data_iter.reset()
ele = next(data_iter)

In [26]:
X, y = get_train_X_y(ele)
y_np = y.asnumpy()
pre = my_lr_network(X).asnumpy()

In [32]:
import numpy as np
label = None
if label is None:
    label = y_np
else:
    label = np.append(label, y_np)

In [41]:
ele2 = next(data_iter)
if label is None:
    label = y_np
else:
    label = np.append(label, y_np)

In [43]:
label

array([ 0.,  1.,  0., ...,  0.,  1.,  0.], dtype=float32)

In [ ]:
import gluon_tool.evaluation

def get_auc(net, data_iter):
    label = None
    pro = None
    for ele in data_iter:
        X, y = get_train_X_y(ele)
        y_np = y.asnumpy()
        pre = net(X).asnumpy()
        if pro is None:
            pro = pre
        else:
            pro = np.append(pro, pre)

        if label is None:
            label = y_np
        else:
            label = np.append(label, y_np)
    t = gluon_tool.evaluation.cal_auc(label, pro)
    return t