# 符号接口训练LR

In [145]:
# 先形成LR的训练数据
import numpy as np
x = np.random.randn(30, 4) * 10

In [146]:
y = np.dot(x, np.array([1, 2, 3, 4])) 
y

array([ -35.72132995,    7.78357826,   30.11685114,  -31.29381902,
        -14.54252202,   12.75898634,  -84.97129643,  -34.52226499,
         -7.95364235,  -17.86344163,  -45.19548646,   60.78553938,
        -90.28514237,  -47.82430712,   30.69760197,    2.75127907,
         55.3460264 ,  -22.95220724,  -42.12872323,  -60.0643531 ,
         64.37715927,  -64.1617118 ,    0.5288583 ,  113.13262334,
         -4.92316597,  -15.64135977,   47.92242149,  -21.69812823,
        -37.41137445,   55.67370424])

In [168]:
y = y + np.array([2]) + np.random.randint(0, 2)
print(y)
y = 1 / (1 + np.exp(-y))
y

[ 2.          2.99997926  3.          2.          2.00000971  2.99999986
  2.          2.          2.00700819  2.00000035  2.          3.          2.
  2.          3.          2.99683136  3.          2.          2.          2.
  3.          2.          2.97149782  3.          2.12750894  2.00000324
  3.          2.00000001  2.          3.        ]


array([ 0.88079708,  0.95257319,  0.95257413,  0.88079708,  0.8807981 ,
        0.95257412,  0.88079708,  0.88079708,  0.88153093,  0.88079711,
        0.88079708,  0.95257413,  0.88079708,  0.88079708,  0.95257413,
        0.95243077,  0.95257413,  0.88079708,  0.88079708,  0.88079708,
        0.95257413,  0.88079708,  0.95126976,  0.95257413,  0.89354829,
        0.88079742,  0.95257413,  0.88079708,  0.88079708,  0.95257413])

In [148]:
x.shape

(30, 4)

In [149]:
y.shape

(30,)

# symbol LR

In [150]:
import mxnet as mx

In [151]:
X_sym = mx.symbol.Variable('inputs')
y_sym = mx.symbol.Variable('label_')

LR的主体部分啊

In [158]:
fully_connected_layer = mx.symbol.FullyConnected(data=X_sym, name='fcl', num_hidden=1)
net = mx.symbol.LogisticRegressionOutput(data=fully_connected_layer, label=y_sym, name="lr_out")

In [159]:
# network structure
model = mx.mod.Module(
    symbol=net,
    data_names=['inputs'],
    label_names=['label_']
)

In [160]:
mx.viz.plot_network(symbol=net)

In [161]:
type(y)

numpy.ndarray

In [169]:
train_iter = mx.io.NDArrayIter(x, y, 3, shuffle=True, data_name='inputs', label_name='label_')
eval_iter = mx.io.NDArrayIter(x, y, 3, shuffle=False)

In [170]:
model.fit(train_iter,
          optimizer_params={'learning_rate':0.5, 'momentum': 0.9},
          num_epoch=50,
          eval_metric='acc')

/mnt/D/Ubuntu/package/anaconda3/lib/python3.6/site-packages/mxnet/module/base_module.py:464: UserWarning: Parameters already initialized and force_init=False. init_params call ignored.
  allow_missing=allow_missing, force_init=force_init)


In [171]:
model.predict(eval_iter).asnumpy()

array([[ 0.88002586],
       [ 0.89809263],
       [ 0.92272103],
       [ 0.86652398],
       [ 0.89990222],
       [ 0.91861576],
       [ 0.83319199],
       [ 0.89731878],
       [ 0.8972137 ],
       [ 0.90268576],
       [ 0.89136493],
       [ 0.93313736],
       [ 0.82484204],
       [ 0.87348044],
       [ 0.91359967],
       [ 0.91870099],
       [ 0.94154978],
       [ 0.87440419],
       [ 0.87819636],
       [ 0.86724859],
       [ 0.93714762],
       [ 0.85652632],
       [ 0.91462463],
       [ 0.94666642],
       [ 0.90127152],
       [ 0.86936289],
       [ 0.93901145],
       [ 0.89443785],
       [ 0.89771575],
       [ 0.93393219]], dtype=float32)

In [181]:
metric = mx.metric.MSE()

In [173]:
model.score(eval_iter, metric)

[('mse', 0.00063094887009356175)]

In [178]:
model.get_params()

({'fcl_bias': 
  [ 2.21349216]
  <NDArray 1 @cpu(0)>, 'fcl_weight': 
  [[-0.00129007  0.0165423   0.02313066  0.01779569]]
  <NDArray 1x4 @cpu(0)>}, {})